language: objective-c
osx_image: xcode10.2
podfile: src/Podfile
xcode_workspace: src/notes.xcworkspace
xcode_scheme: notes
xcode_destination: platform=iOS Simulator,OS=12.0,name=iPhone X

before_install:
  - gem install cocoapods --pre
  - pod repo update
